/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package retoclase;

import java.awt.event.KeyEvent;
/**
 *
 * @author Estudiante
 */

public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        jLabel1.setVisible(true);
        jLabel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/retoclase/noMoveOriginal.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 60, 200, 170);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/retoclase/moveOriginal.png"))); // NOI18N
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 260, 220, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int code = evt.getKeyCode();
        jLabel1.setVisible(false);
        jLabel2.setVisible(true);
        switch(code) {
            case KeyEvent.VK_LEFT -> jLabel2.setBounds(jLabel2.getX()-5,jLabel2.getY(),jLabel2.getWidth(),jLabel2.getHeight());
            //handle left arrow key
            case KeyEvent.VK_RIGHT -> jLabel2.setBounds(jLabel2.getX()+5,jLabel2.getY(),jLabel2.getWidth(),jLabel2.getHeight());
            //handle right arrow
            case KeyEvent.VK_UP -> jLabel2.setBounds(jLabel2.getX(),jLabel2.getY()-5,jLabel2.getWidth(),jLabel2.getHeight());
            //handle up arrow
            case KeyEvent.VK_DOWN -> jLabel2.setBounds(jLabel2.getX(),jLabel2.getY()+5,jLabel2.getWidth(),jLabel2.getHeight());
            //handle down arrow
            default -> {
            }
        }
    }//GEN-LAST:event_formKeyPressed
    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        jLabel1.setVisible(true);
        jLabel1.setBounds(jLabel2.getX(),jLabel2.getY(),jLabel2.getWidth(),jLabel2.getHeight());
    }//GEN-LAST:event_formKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
